language: R
sudo: true
cache: packages
dist: xenial

addons:
  apt:
    packages:
      - libgit2-dev

notifications:
  slack: tadaadata:I5XxVZ1gO6B1s0xTjPDQVw0t

r:
  #- oldrel # can't install mvtnorm
  - release
  - devel

r_binary_packages:
  - testthat
  - jsonlite
  - git2r
  - ps
  - processx
  - httr
  - dplyr
  - lubridate
  - purrr
  - stringr
  - stringi
  - ggplot2
  - knitr
  - rmarkdown
  - commonmark
  - highlight
  - xml2
  - roxygen2
  - assertthat
  - glue
  - openssl
  - rlang

after_success:
  - Rscript -e 'covr::codecov()'

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(run_dont_run = FALSE)'
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_R_VERSION_STRING = release"
