---
title: "Package Dependencies"
author: "@jemus42"
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_height: 6
    fig_width: 9
---

## DiagrammeR circo graph of dependencies

```{r, echo=F}
library(tools)
library(DiagrammeR)
library(networkD3)
library(magrittr)

dep1 <- package_dependencies("tadaatoolbox", db = available.packages(), recursive = F)
dep2 <- lapply(dep1[[1]], package_dependencies, db = available.packages())

nodes_total <- c("tadaatoolbox", dep1[[1]], unique(unlist(sapply(dep2, "[[", 1))))

from1 <- rep("tadaatoolbox", length(dep1[[1]]))
from2 <- unlist(sapply(dep2, function(x){
  rep(names(x), length(x[[1]]))
}))

from_pkgs <- c(from1, from2)

to_pkgs <- c(dep1[[1]],
             unlist(sapply(dep2, function(x){x[[1]]}))
             )


graph <- create_graph(nodes_df = create_nodes(nodes_total),
                      edges_df = create_edges(from = from_pkgs,
                                              to = to_pkgs,
                                              rel = "to_get",
                                              "penwidth = 2"),
                      graph_attrs = c("layout = circo",
                                      "overlap = false",
                                      "outputorder = edgesfirst")
                      )
render_graph(graph = graph)
```

## networkD3 simplenetwork

```{r, echo=F}
as.data.frame(cbind(from_pkgs, to_pkgs)) %>%
  simpleNetwork(Data = ., Source = "from_pkgs", Target = "to_pkgs",
                linkDistance = 100, zoom = TRUE)

```
